SELECT * FROM Deliveries

INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (1, 'Berlin-Paris', '10:00:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (2, 'Madrid-Lisbon', '12:30:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (3, 'Rome-Athens', '15:45:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (4, 'London-Amsterdam', '08:15:00', 'Delayed');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (5, 'Paris-Prague', '11:00:00', 'Finished');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (6, 'Vienna-Budapest', '14:20:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (7, 'Brussels-Amsterdam', '09:45:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (8, 'Warsaw-Prague', '13:30:00', 'Delayed');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (9, 'Oslo-Stockholm', '16:10:00', 'Finished');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (10, 'Copenhagen-Berlin', '10:30:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (11, 'Budapest-Amsterdam', '11:50:00', 'Delayed');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (12, 'Prague-Copenhagen', '09:15:00', 'Finished');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (13, 'Stockholm-Warsaw', '14:30:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (14, 'Ljubljana-Brussels', '12:00:00', 'Finished');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (15, 'Berlin-Paris', '10:00:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (16, 'London-Madrid', '12:30:00', 'Delayed');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (17, 'Rome-Budapest', '09:45:00', 'Finished');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (18, 'Amsterdam-Vienna', '11:15:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (19, 'Paris-Prague', '14:20:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (20, 'Copenhagen-Stockholm', '16:40:00', 'Delayed');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (21, 'Warsaw-Ljubljana', '13:10:00', 'Finished');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (22, 'Brussels-Berlin', '10:45:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (23, 'Madrid-London', '08:30:00', 'Finished');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (24, 'Vienna-Rome', '15:00:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (25, 'Budapest-Amsterdam', '11:50:00', 'Delayed');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (26, 'Prague-Copenhagen', '09:15:00', 'Finished');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (27, 'Stockholm-Warsaw', '14:30:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (28, 'Ljubljana-Brussels', '12:00:00', 'Finished');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (29, 'Berlin-Paris', '10:00:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (30, 'London-Madrid', '12:30:00', 'Delayed');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (31, 'Rome-Budapest', '09:45:00', 'Finished');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (32, 'Amsterdam-Vienna', '11:15:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (33, 'Paris-Prague', '14:20:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (34, 'Copenhagen-Stockholm', '16:40:00', 'Delayed');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (35, 'Warsaw-Ljubljana', '13:10:00', 'Finished');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (36, 'Brussels-Berlin', '10:45:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (37, 'Madrid-London', '08:30:00', 'Finished');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (38, 'Vienna-Rome', '15:00:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (39, 'Budapest-Amsterdam', '11:50:00', 'Delayed');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (40, 'Prague-Copenhagen', '09:15:00', 'Finished');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (41, 'Stockholm-Warsaw', '14:30:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (42, 'Ljubljana-Brussels', '12:00:00', 'Finished');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (43, 'Berlin-Paris', '10:00:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (44, 'London-Madrid', '12:30:00', 'Delayed');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (45, 'Rome-Budapest', '09:45:00', 'Finished');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (46, 'Amsterdam-Vienna', '11:15:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (47, 'Paris-Prague', '14:20:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (48, 'Copenhagen-Stockholm', '16:40:00', 'Delayed');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (49, 'Warsaw-Ljubljana', '13:10:00', 'Finished');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (50, 'Brussels-Berlin', '10:45:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (51, 'Amsterdam-Lisbon', '14:45:00', 'Finished');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (52, 'Barcelona-Rome', '09:20:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (53, 'Berlin-Warsaw', '12:10:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (54, 'Prague-Vienna', '15:30:00', 'Delayed');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (55, 'Stockholm-Oslo', '08:45:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (56, 'Athens-Madrid', '11:15:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (57, 'Lisbon-Paris', '14:40:00', 'Delayed');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (58, 'Budapest-Copenhagen', '10:00:00', 'Finished');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (59, 'Prague-Brussels', '13:25:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (60, 'London-Berlin', '16:05:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (61, 'Paris-Prague', '14:20:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (62, 'Copenhagen-Stockholm', '16:40:00', 'Delayed');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (63, 'Warsaw-Ljubljana', '13:10:00', 'Finished');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (64, 'Brussels-Berlin', '10:45:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (65, 'Madrid-London', '08:30:00', 'Finished');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (66, 'Vienna-Rome', '15:00:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (67, 'Budapest-Amsterdam', '11:50:00', 'Delayed');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (68, 'Prague-Copenhagen', '09:15:00', 'Finished');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (69, 'Stockholm-Warsaw', '14:30:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (70, 'Ljubljana-Brussels', '12:00:00', 'Finished');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (71, 'Berlin-Paris', '10:00:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (72, 'London-Madrid', '12:30:00', 'Delayed');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (73, 'Rome-Budapest', '09:45:00', 'Finished');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (74, 'Amsterdam-Vienna', '11:15:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (75, 'Paris-Prague', '14:20:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (76, 'Copenhagen-Stockholm', '16:40:00', 'Delayed');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (77, 'Warsaw-Ljubljana', '13:10:00', 'Finished');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (78, 'Brussels-Berlin', '10:45:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (79, 'Madrid-London', '08:30:00', 'Finished');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (80, 'Vienna-Rome', '15:00:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (81, 'Budapest-Amsterdam', '11:50:00', 'Delayed');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (82, 'Prague-Copenhagen', '09:15:00', 'Finished');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (83, 'Stockholm-Warsaw', '14:30:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (84, 'Ljubljana-Brussels', '12:00:00', 'Finished');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (85, 'Berlin-Paris', '10:00:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (86, 'London-Madrid', '12:30:00', 'Delayed');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (87, 'Rome-Budapest', '09:45:00', 'Finished');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (88, 'Amsterdam-Vienna', '11:15:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (89, 'Paris-Prague', '14:20:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (90, 'Copenhagen-Stockholm', '16:40:00', 'Delayed');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (91, 'Warsaw-Ljubljana', '13:10:00', 'Finished');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (92, 'Brussels-Berlin', '10:45:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (93, 'Madrid-London', '08:30:00', 'Finished');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (94, 'Vienna-Rome', '15:00:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (95, 'Budapest-Amsterdam', '11:50:00', 'Delayed');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (96, 'Prague-Copenhagen', '09:15:00', 'Finished');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (97, 'Stockholm-Warsaw', '14:30:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (98, 'Ljubljana-Brussels', '12:00:00', 'Finished');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (99, 'Berlin-Paris', '10:00:00', 'On going');
INSERT INTO Deliveries (DeliveryID, Destination, ETA, Status) VALUES (100, 'London-Madrid', '12:30:00', 'Delayed');