INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (1, N'Berlin-Paris', N'10:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (2, N'Madrid-Lisbon', N'12:30:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (3, N'Rome-Athens', N'15:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (4, N'London-Amsterdam', N'08:15:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (5, N'Paris-Prague', N'11:00:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (6, N'Vienna-Budapest', N'14:20:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (7, N'Brussels-Amsterdam', N'09:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (8, N'Warsaw-Prague', N'13:30:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (9, N'Oslo-Stockholm', N'16:10:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (10, N'Copenhagen-Berlin', N'10:30:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (11, N'Budapest-Amsterdam', N'11:50:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (12, N'Prague-Copenhagen', N'09:15:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (13, N'Stockholm-Warsaw', N'14:30:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (14, N'Ljubljana-Brussels', N'12:00:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (15, N'Berlin-Paris', N'10:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (16, N'London-Madrid', N'12:30:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (17, N'Rome-Budapest', N'09:45:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (18, N'Amsterdam-Vienna', N'11:15:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (19, N'Paris-Prague', N'14:20:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (20, N'Copenhagen-Stockholm', N'16:40:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (21, N'Warsaw-Ljubljana', N'13:10:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (22, N'Brussels-Berlin', N'10:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (23, N'Madrid-London', N'08:30:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (24, N'Vienna-Rome', N'15:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (25, N'Budapest-Amsterdam', N'11:50:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (26, N'Prague-Copenhagen', N'09:15:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (27, N'Stockholm-Warsaw', N'14:30:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (28, N'Ljubljana-Brussels', N'12:00:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (29, N'Berlin-Paris', N'10:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (30, N'London-Madrid', N'12:30:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (31, N'Rome-Budapest', N'09:45:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (32, N'Amsterdam-Vienna', N'11:15:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (33, N'Paris-Prague', N'14:20:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (34, N'Copenhagen-Stockholm', N'16:40:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (35, N'Warsaw-Ljubljana', N'13:10:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (36, N'Brussels-Berlin', N'10:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (37, N'Madrid-London', N'08:30:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (38, N'Vienna-Rome', N'15:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (39, N'Budapest-Amsterdam', N'11:50:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (40, N'Prague-Copenhagen', N'09:15:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (41, N'Stockholm-Warsaw', N'14:30:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (42, N'Ljubljana-Brussels', N'12:00:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (43, N'Berlin-Paris', N'10:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (44, N'London-Madrid', N'12:30:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (45, N'Rome-Budapest', N'09:45:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (46, N'Amsterdam-Vienna', N'11:15:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (47, N'Paris-Prague', N'14:20:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (48, N'Copenhagen-Stockholm', N'16:40:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (49, N'Warsaw-Ljubljana', N'13:10:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (50, N'Brussels-Berlin', N'10:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (51, N'Amsterdam-Lisbon', N'14:45:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (52, N'Barcelona-Rome', N'09:20:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (53, N'Berlin-Warsaw', N'12:10:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (54, N'Prague-Vienna', N'15:30:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (55, N'Stockholm-Oslo', N'08:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (56, N'Athens-Madrid', N'11:15:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (57, N'Lisbon-Paris', N'14:40:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (58, N'Budapest-Copenhagen', N'10:00:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (59, N'Prague-Brussels', N'13:25:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (60, N'London-Berlin', N'16:05:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (61, N'Paris-Prague', N'14:20:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (62, N'Copenhagen-Stockholm', N'16:40:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (63, N'Warsaw-Ljubljana', N'13:10:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (64, N'Brussels-Berlin', N'10:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (65, N'Madrid-London', N'08:30:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (66, N'Vienna-Rome', N'15:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (67, N'Budapest-Amsterdam', N'11:50:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (68, N'Prague-Copenhagen', N'09:15:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (69, N'Stockholm-Warsaw', N'14:30:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (70, N'Ljubljana-Brussels', N'12:00:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (71, N'Berlin-Paris', N'10:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (72, N'London-Madrid', N'12:30:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (73, N'Rome-Budapest', N'09:45:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (74, N'Amsterdam-Vienna', N'11:15:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (75, N'Paris-Prague', N'14:20:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (76, N'Copenhagen-Stockholm', N'16:40:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (77, N'Warsaw-Ljubljana', N'13:10:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (78, N'Brussels-Berlin', N'10:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (79, N'Madrid-London', N'08:30:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (80, N'Vienna-Rome', N'15:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (81, N'Budapest-Amsterdam', N'11:50:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (82, N'Prague-Copenhagen', N'09:15:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (83, N'Stockholm-Warsaw', N'14:30:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (84, N'Ljubljana-Brussels', N'12:00:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (85, N'Berlin-Paris', N'10:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (86, N'London-Madrid', N'12:30:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (87, N'Rome-Budapest', N'09:45:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (88, N'Amsterdam-Vienna', N'11:15:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (89, N'Paris-Prague', N'14:20:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (90, N'Copenhagen-Stockholm', N'16:40:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (91, N'Warsaw-Ljubljana', N'13:10:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (92, N'Brussels-Berlin', N'10:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (93, N'Madrid-London', N'08:30:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (94, N'Vienna-Rome', N'15:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (95, N'Budapest-Amsterdam', N'11:50:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (96, N'Prague-Copenhagen', N'09:15:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (97, N'Stockholm-Warsaw', N'14:30:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (98, N'Ljubljana-Brussels', N'12:00:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (99, N'Berlin-Paris', N'10:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (100, N'London-Madrid', N'12:30:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (101, N'Berlin-Paris', N'10:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (102, N'London-Madrid', N'12:30:00', N'Scheduled')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (103, N'Rome-Amsterdam', N'15:45:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (104, N'New York-Los Angeles', N'18:20:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (105, N'Tokyo-Sydney', N'21:10:00', N'Scheduled')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (106, N'Paris-Berlin', N'09:30:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (107, N'Madrid-London', N'14:00:00', N'Scheduled')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (108, N'Amsterdam-Rome', N'16:30:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (109, N'Los Angeles-New York', N'20:45:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (110, N'Sydney-Tokyo', N'22:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (111, N'Berlin-London', N'11:15:00', N'Scheduled')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (112, N'Paris-Rome', N'13:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (113, N'Madrid-Amsterdam', N'17:00:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (114, N'New York-Tokyo', N'19:30:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (115, N'Los Angeles-Sydney', N'23:00:00', N'Scheduled')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (116, N'London-Berlin', N'08:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (117, N'Rome-Paris', N'12:15:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (118, N'Amsterdam-Madrid', N'15:30:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (119, N'Tokyo-New York', N'18:45:00', N'Scheduled')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (120, N'Sydney-Los Angeles', N'21:15:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (121, N'Berlin-Paris', N'10:30:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (122, N'London-Madrid', N'13:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (123, N'Rome-Amsterdam', N'16:15:00', N'Scheduled')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (124, N'New York-Los Angeles', N'19:30:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (125, N'Tokyo-Sydney', N'22:00:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (126, N'Paris-Berlin', N'09:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (127, N'Madrid-London', N'14:15:00', N'Scheduled')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (128, N'Amsterdam-Rome', N'17:30:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (129, N'Los Angeles-New York', N'20:45:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (130, N'Sydney-Tokyo', N'23:15:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (131, N'Berlin-London', N'11:30:00', N'Scheduled')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (132, N'Paris-Rome', N'14:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (133, N'Madrid-Amsterdam', N'17:15:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (134, N'New York-Tokyo', N'19:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (135, N'Los Angeles-Sydney', N'23:30:00', N'Scheduled')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (136, N'London-Berlin', N'09:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (137, N'Rome-Paris', N'12:30:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (138, N'Amsterdam-Madrid', N'15:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (139, N'Tokyo-New York', N'19:00:00', N'Scheduled')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (140, N'Sydney-Los Angeles', N'21:30:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (141, N'Berlin-Paris', N'10:45:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (142, N'London-Madrid', N'13:15:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (143, N'Rome-Amsterdam', N'16:30:00', N'Scheduled')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (144, N'New York-Los Angeles', N'19:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (145, N'Tokyo-Sydney', N'22:15:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (146, N'Paris-Berlin', N'10:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (147, N'Madrid-London', N'14:30:00', N'Scheduled')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (148, N'Amsterdam-Rome', N'17:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (149, N'Los Angeles-New York', N'21:00:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (150, N'Sydney-Tokyo', N'23:30:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (151, N'London-Amsterdam', N'10:30:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (152, N'New York-Paris', N'13:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (153, N'Rome-Tokyo', N'16:15:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (154, N'Berlin-Los Angeles', N'19:30:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (155, N'Sydney-Madrid', N'22:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (156, N'Amsterdam-Berlin', N'09:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (157, N'Tokyo-Paris', N'14:15:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (158, N'London-Rome', N'17:30:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (159, N'New York-Sydney', N'20:45:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (160, N'Los Angeles-Madrid', N'23:15:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (161, N'Paris-Berlin', N'11:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (162, N'Amsterdam-London', N'13:30:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (163, N'Rome-New York', N'16:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (164, N'Tokyo-Los Angeles', N'20:00:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (165, N'Sydney-Madrid', N'22:30:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (166, N'Berlin-Paris', N'10:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (167, N'London-Madrid', N'13:15:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (168, N'Rome-Amsterdam', N'16:30:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (169, N'New York-Los Angeles', N'19:45:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (170, N'Tokyo-Sydney', N'22:15:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (171, N'Paris-Berlin', N'10:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (172, N'Madrid-London', N'14:30:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (173, N'Amsterdam-Rome', N'17:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (174, N'Los Angeles-New York', N'21:00:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (175, N'Sydney-Tokyo', N'23:30:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (176, N'Berlin-Paris', N'11:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (177, N'London-Madrid', N'13:30:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (178, N'Rome-Amsterdam', N'16:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (179, N'New York-Los Angeles', N'20:00:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (180, N'Tokyo-Sydney', N'22:30:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (181, N'Paris-Berlin', N'11:15:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (182, N'Madrid-London', N'14:45:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (183, N'Amsterdam-Rome', N'18:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (184, N'Los Angeles-New York', N'21:15:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (185, N'Sydney-Tokyo', N'23:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (186, N'Berlin-Paris', N'11:30:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (187, N'London-Madrid', N'14:00:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (188, N'Rome-Amsterdam', N'17:15:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (189, N'New York-Los Angeles', N'20:30:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (190, N'Tokyo-Sydney', N'23:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (191, N'Paris-Berlin', N'11:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (192, N'Madrid-London', N'15:15:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (193, N'Amsterdam-Rome', N'18:30:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (194, N'Los Angeles-New York', N'21:45:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (195, N'Sydney-Tokyo', N'00:15:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (196, N'Berlin-Paris', N'12:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (197, N'London-Madrid', N'14:30:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (198, N'Rome-Amsterdam', N'17:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (199, N'New York-Los Angeles', N'21:00:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (200, N'Tokyo-Sydney', N'00:30:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (201, N'Paris-Berlin', N'12:15:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (202, N'Madrid-London', N'15:45:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (203, N'Amsterdam-Rome', N'19:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (204, N'Los Angeles-New York', N'22:15:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (205, N'Sydney-Tokyo', N'00:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (206, N'Berlin-Paris', N'10:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (207, N'London-Madrid', N'12:30:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (208, N'Rome-Amsterdam', N'15:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (209, N'New York-Los Angeles', N'18:20:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (210, N'Tokyo-Sydney', N'21:10:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (211, N'Paris-Berlin', N'09:30:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (212, N'Madrid-London', N'14:00:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (213, N'Amsterdam-Rome', N'16:30:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (214, N'Los Angeles-New York', N'20:45:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (215, N'Sydney-Tokyo', N'22:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (216, N'Berlin-Lisbon', N'11:15:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (217, N'Paris-Munich', N'13:45:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (218, N'Madrid-Brussels', N'17:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (219, N'Los Angeles-Chicago', N'19:30:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (220, N'Sydney-Melbourne', N'22:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (221, N'Amsterdam-Prague', N'09:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (222, N'London-Edinburgh', N'14:15:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (223, N'New York-Miami', N'17:30:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (224, N'Rome-Athens', N'20:45:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (225, N'Tokyo-Osaka', N'22:15:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (226, N'Berlin-Vienna', N'10:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (227, N'Paris-Barcelona', N'13:30:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (228, N'Madrid-Porto', N'16:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (229, N'Los Angeles-San Francisco', N'20:00:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (230, N'Sydney-Brisbane', N'22:30:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (231, N'Amsterdam-Budapest', N'11:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (232, N'London-Paris', N'15:15:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (233, N'New York-Washington DC', N'18:30:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (234, N'Rome-Venice', N'21:45:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (235, N'Tokyo-Kyoto', N'23:15:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (236, N'Berlin-Stockholm', N'12:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (237, N'Paris-Nice', N'14:30:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (238, N'Madrid-Seville', N'17:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (239, N'Los Angeles-Las Vegas', N'21:00:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (240, N'Sydney-Canberra', N'23:30:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (241, N'Amsterdam-Bruges', N'10:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (242, N'London-Manchester', N'14:00:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (243, N'New York-Boston', N'17:15:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (244, N'Rome-Naples', N'20:30:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (245, N'Tokyo-Hiroshima', N'22:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (246, N'Berlin-Copenhagen', N'11:30:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (247, N'Paris-Lyon', N'14:45:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (248, N'Madrid-Granada', N'18:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (249, N'Los Angeles-Phoenix', N'21:15:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (250, N'Burgas-Istanbul', N'10:35:12', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (251, N'Amsterdam-Rotterdam', N'12:15:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (252, N'London-Glasgow', N'15:30:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (253, N'New York-Philadelphia', N'18:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (254, N'Rome-Florence', N'22:00:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (255, N'Tokyo-Osaka', N'23:30:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (256, N'Berlin-Brussels', N'12:30:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (257, N'Paris-Amsterdam', N'15:45:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (258, N'Madrid-Barcelona', N'19:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (259, N'Los Angeles-San Diego', N'21:30:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (260, N'Sydney-Perth', N'00:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (261, N'Amsterdam-Maastricht', N'12:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (262, N'London-Bristol', N'16:00:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (263, N'New York-Chicago', N'19:15:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (264, N'Rome-Milan', N'22:30:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (265, N'Tokyo-Nagoya', N'00:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (266, N'Berlin-Hamburg', N'13:15:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (267, N'Paris-Strasbourg', N'16:30:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (268, N'Madrid-Valencia', N'19:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (269, N'Los Angeles-Seattle', N'23:00:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (270, N'Sydney-Canberra', N'01:30:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (271, N'Amsterdam-Utrecht', N'13:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (272, N'London-Oxford', N'17:00:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (273, N'New York-Atlanta', N'20:15:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (274, N'Rome-Turin', N'23:30:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (275, N'Tokyo-Fukuoka', N'01:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (276, N'Berlin-Leipzig', N'14:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (277, N'Paris-Lille', N'17:15:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (278, N'Madrid-Seville', N'20:30:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (279, N'Los Angeles-Portland', N'23:45:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (280, N'Sydney-Brisbane', N'02:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (281, N'Amsterdam-Rotterdam', N'14:15:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (282, N'London-Cambridge', N'17:30:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (283, N'New York-Dallas', N'20:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (284, N'Rome-Pisa', N'00:00:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (285, N'Tokyo-Sapporo', N'02:15:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (286, N'Berlin-Frankfurt', N'14:30:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (287, N'Paris-Nantes', N'17:45:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (288, N'Madrid-Malaga', N'21:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (289, N'Los Angeles-Denver', N'00:15:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (290, N'Sydney-Adelaide', N'02:30:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (291, N'Amsterdam-The Hague', N'15:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (292, N'London-Edinburgh', N'18:15:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (293, N'New York-Houston', N'21:30:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (294, N'Rome-Genoa', N'00:45:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (295, N'Tokyo-Osaka', N'03:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (296, N'Berlin-Dresden', N'15:15:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (297, N'Paris-Marseille', N'18:30:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (298, N'Madrid-Zaragoza', N'21:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (299, N'Los Angeles-Phoenix', N'01:00:00', N'Finished')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (300, N'Sydney-Perth', N'03:15:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (301, N'Berlin-Burgas', N'10:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (302, N'Berlin-Burgas', N'10:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (303, N'Paris-Madrid', N'12:30:00', N'Scheduled')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (304, N'London-Rome', N'14:45:00', N'Completed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (305, N'Amsterdam-Vienna', N'11:15:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (306, N'Prague-Warsaw', N'16:20:00', N'Scheduled')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (307, N'Brussels-Bucharest', N'13:10:00', N'Completed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (308, N'Copenhagen-Athens', N'15:30:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (309, N'Oslo-Stockholm', N'09:45:00', N'Scheduled')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (310, N'Helsinki-Lisbon', N'17:50:00', N'Completed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (311, N'Dublin-Bratislava', N'08:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (312, N'Vienna-Zurich', N'18:30:00', N'Scheduled')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (313, N'Budapest-Riga', N'14:00:00', N'Completed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (314, N'Barcelona-Edinburgh', N'10:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (315, N'Lisbon-Oslo', N'19:15:00', N'Scheduled')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (316, N'Rome-Copenhagen', N'11:30:00', N'Completed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (317, N'Hamburg-Athens', N'20:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (318, N'Warsaw-London', N'13:45:00', N'Scheduled')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (319, N'Madrid-Prague', N'09:30:00', N'Completed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (320, N'Munich-Stockholm', N'15:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (321, N'Zurich-Paris', N'21:30:00', N'Scheduled')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (322, N'Bucharest-Berlin', N'16:45:00', N'Completed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (323, N'Edinburgh-Lisbon', N'12:15:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (324, N'Athens-Dublin', N'22:00:00', N'Scheduled')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (325, N'Bratislava-Brussels', N'17:30:00', N'Completed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (326, N'Riga-Barcelona', N'13:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (327, N'Cologne-Budapest', N'23:45:00', N'Scheduled')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (328, N'Lyon-Helsinki', N'18:15:00', N'Completed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (329, N'Glasgow-Prague', N'14:30:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (330, N'Amsterdam-Warsaw', N'00:15:00', N'Scheduled')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (331, N'Frankfurt-Oslo', N'19:45:00', N'Completed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (332, N'Seville-Stockholm', N'15:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (333, N'Turin-Lisbon', N'01:30:00', N'Scheduled')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (334, N'Krakow-Copenhagen', N'20:45:00', N'Completed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (335, N'Vienna-Edinburgh', N'16:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (336, N'Budapest-Berlin', N'02:15:00', N'Scheduled')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (337, N'Marseille-Prague', N'21:30:00', N'Completed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (338, N'Copenhagen-Oslo', N'17:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (339, N'Rome-Stockholm', N'03:00:00', N'Scheduled')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (340, N'Warsaw-Brussels', N'22:15:00', N'Completed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (341, N'Madrid-Budapest', N'18:30:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (342, N'Hamburg-Prague', N'04:45:00', N'Scheduled')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (343, N'Zurich-Lisbon', N'23:00:00', N'Completed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (344, N'Berlin-Bratislava', N'20:15:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (345, N'Paris-Barcelona', N'06:30:00', N'Scheduled')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (346, N'London-Bucharest', N'01:45:00', N'Completed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (347, N'Amsterdam-Athens', N'21:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (348, N'Barcelona-Rome', N'08:45:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (349, N'Vienna-Paris', N'10:30:00', N'Scheduled')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (350, N'Lisbon-Madrid', N'14:00:00', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (351, N'Grenada-Venice', N'08:25:00', N'Delayed')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (352, N'Valencia-Lisbon', N'14:00:00', N'Delivered')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (353, N'Burgas-Plovdiv', N'06:35:00', N'Delivered')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (354, N'Brashov-Budapest', N'05:07:25', N'On going')
INSERT INTO [dbo].[Deliveries] ([DeliveryID], [Destination], [ETA], [Status]) VALUES (355, N'Washington-Texas', N'11:11:00', N'On going')

SET IDENTITY_INSERT [dbo].[Deliveries] ON

CREATE TABLE [dbo].[Deliveries] (
    [DeliveryID]  INT            IDENTITY (1, 1) NOT NULL,
    [Destination] NVARCHAR (MAX) NOT NULL,
    [ETA]         NVARCHAR (MAX) NOT NULL,
    [Status]      NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_Deliveries] PRIMARY KEY CLUSTERED ([DeliveryID] ASC)
);

