INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (54, CAST(150.75 AS Decimal(18, 2)), N'January')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (55, CAST(200.50 AS Decimal(18, 2)), N'February')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (56, CAST(75.25 AS Decimal(18, 2)), N'March')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (57, CAST(300.00 AS Decimal(18, 2)), N'April')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (58, CAST(120.00 AS Decimal(18, 2)), N'May')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (59, CAST(180.50 AS Decimal(18, 2)), N'June')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (60, CAST(220.25 AS Decimal(18, 2)), N'July')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (61, CAST(90.75 AS Decimal(18, 2)), N'August')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (62, CAST(250.00 AS Decimal(18, 2)), N'September')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (63, CAST(300.00 AS Decimal(18, 2)), N'October')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (64, CAST(160.25 AS Decimal(18, 2)), N'November')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (65, CAST(130.50 AS Decimal(18, 2)), N'December')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (66, CAST(270.75 AS Decimal(18, 2)), N'January')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (67, CAST(200.00 AS Decimal(18, 2)), N'February')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (68, CAST(110.00 AS Decimal(18, 2)), N'March')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (69, CAST(240.50 AS Decimal(18, 2)), N'April')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (70, CAST(180.25 AS Decimal(18, 2)), N'May')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (71, CAST(130.75 AS Decimal(18, 2)), N'June')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (72, CAST(290.00 AS Decimal(18, 2)), N'July')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (73, CAST(170.50 AS Decimal(18, 2)), N'August')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (74, CAST(90.25 AS Decimal(18, 2)), N'September')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (75, CAST(210.75 AS Decimal(18, 2)), N'October')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (76, CAST(260.00 AS Decimal(18, 2)), N'November')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (77, CAST(150.50 AS Decimal(18, 2)), N'December')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (78, CAST(120.00 AS Decimal(18, 2)), N'January')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (79, CAST(280.25 AS Decimal(18, 2)), N'February')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (80, CAST(230.75 AS Decimal(18, 2)), N'March')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (81, CAST(190.00 AS Decimal(18, 2)), N'April')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (82, CAST(110.50 AS Decimal(18, 2)), N'May')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (83, CAST(320.75 AS Decimal(18, 2)), N'June')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (84, CAST(260.00 AS Decimal(18, 2)), N'July')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (85, CAST(150.50 AS Decimal(18, 2)), N'August')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (86, CAST(120.00 AS Decimal(18, 2)), N'September')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (87, CAST(280.25 AS Decimal(18, 2)), N'October')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (88, CAST(230.75 AS Decimal(18, 2)), N'November')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (89, CAST(190.00 AS Decimal(18, 2)), N'December')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (90, CAST(110.50 AS Decimal(18, 2)), N'January')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (91, CAST(320.75 AS Decimal(18, 2)), N'February')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (92, CAST(260.00 AS Decimal(18, 2)), N'March')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (93, CAST(150.50 AS Decimal(18, 2)), N'April')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (94, CAST(120.00 AS Decimal(18, 2)), N'May')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (95, CAST(280.25 AS Decimal(18, 2)), N'June')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (96, CAST(230.75 AS Decimal(18, 2)), N'July')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (97, CAST(190.00 AS Decimal(18, 2)), N'August')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (98, CAST(110.50 AS Decimal(18, 2)), N'September')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (99, CAST(320.75 AS Decimal(18, 2)), N'October')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (100, CAST(260.00 AS Decimal(18, 2)), N'November')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (101, CAST(150.50 AS Decimal(18, 2)), N'December')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (102, CAST(120.00 AS Decimal(18, 2)), N'January')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (103, CAST(280.25 AS Decimal(18, 2)), N'February')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (104, CAST(230.75 AS Decimal(18, 2)), N'March')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (105, CAST(190.00 AS Decimal(18, 2)), N'April')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (106, CAST(110.50 AS Decimal(18, 2)), N'May')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (107, CAST(320.75 AS Decimal(18, 2)), N'June')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (108, CAST(260.00 AS Decimal(18, 2)), N'July')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (109, CAST(150.50 AS Decimal(18, 2)), N'August')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (110, CAST(120.00 AS Decimal(18, 2)), N'September')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (111, CAST(280.25 AS Decimal(18, 2)), N'October')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (112, CAST(230.75 AS Decimal(18, 2)), N'November')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (113, CAST(190.00 AS Decimal(18, 2)), N'December')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (114, CAST(110.50 AS Decimal(18, 2)), N'January')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (115, CAST(320.75 AS Decimal(18, 2)), N'February')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (116, CAST(260.00 AS Decimal(18, 2)), N'March')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (117, CAST(150.50 AS Decimal(18, 2)), N'April')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (118, CAST(120.00 AS Decimal(18, 2)), N'May')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (119, CAST(280.25 AS Decimal(18, 2)), N'June')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (120, CAST(230.75 AS Decimal(18, 2)), N'July')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (121, CAST(190.00 AS Decimal(18, 2)), N'August')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (122, CAST(110.50 AS Decimal(18, 2)), N'September')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (123, CAST(320.75 AS Decimal(18, 2)), N'October')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (124, CAST(260.00 AS Decimal(18, 2)), N'November')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (125, CAST(150.50 AS Decimal(18, 2)), N'December')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (126, CAST(120.00 AS Decimal(18, 2)), N'January')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (127, CAST(280.25 AS Decimal(18, 2)), N'February')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (128, CAST(230.75 AS Decimal(18, 2)), N'March')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (129, CAST(190.00 AS Decimal(18, 2)), N'April')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (130, CAST(110.50 AS Decimal(18, 2)), N'May')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (131, CAST(320.75 AS Decimal(18, 2)), N'June')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (132, CAST(260.00 AS Decimal(18, 2)), N'July')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (133, CAST(150.50 AS Decimal(18, 2)), N'August')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (134, CAST(120.00 AS Decimal(18, 2)), N'September')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (135, CAST(280.25 AS Decimal(18, 2)), N'October')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (136, CAST(230.75 AS Decimal(18, 2)), N'November')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (137, CAST(190.00 AS Decimal(18, 2)), N'December')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (138, CAST(110.50 AS Decimal(18, 2)), N'January')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (139, CAST(320.75 AS Decimal(18, 2)), N'February')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (140, CAST(260.00 AS Decimal(18, 2)), N'March')
INSERT INTO [dbo].[Revenue] ([RevenueID], [Amount], [Month]) VALUES (141, CAST(150.50 AS Decimal(18, 2)), N'April')

SET IDENTITY_INSERT [dbo].[Revenue] ON

CREATE TABLE [dbo].[Revenue] (
    [RevenueID] INT             NOT NULL,
    [Amount]    DECIMAL (18, 2) NOT NULL,
    [Month]     NVARCHAR (MAX)  NOT NULL,
    CONSTRAINT [PK_Revenue] PRIMARY KEY CLUSTERED ([RevenueID] ASC),
    CONSTRAINT [UQ_Revenue_DeliveryID] UNIQUE NONCLUSTERED ([RevenueID] ASC),
    CONSTRAINT [FK_Revenue_Deliveries] FOREIGN KEY ([RevenueID]) REFERENCES [dbo].[Deliveries] ([DeliveryID])
);

